### ISSUE TITLE
DropGalaxy no longer working

### ISSUE THREAD

**Issue by p4w4n** [PrimePlaya24/dl-site-scrubber#10]
After waiting the page is redirected but the redirected page always shows the message as adblock detected. I tried turning ON/OFF the UBlock Origin but didn't help.

Any suggestions?

**Comment by PrimePlaya24** [comment]
Removed support for DropGalaxy

**Comment by PrimePlaya24** [comment]
Resolved in [v2.1.4](https://github.com/PrimePlaya24/dl-site-scrubber/commit/2b8ddc65750d8096034b3738d87acf94b2b6601e)
