### ISSUE TITLE
Triggers Adblock detection on Dropgalaxy

### ISSUE THREAD

**Issue by vishupal4185** [PrimePlaya24/dl-site-scrubber#11]
As the title says, the site scrubber  script triggers adblock detection even if it is disabled on dropgalaxy links. The site works perfectly and allows downloading when site scrubber is disabled and even adguard enabled.

**Comment by Mushfiq2002** [comment]
are there any other way to bypass drop galaxy?

**Comment by vishupal4185** [comment]
> are there any other way to bypass drop galaxy?

@Mushfiq2002 I use Adguard for windows and it bypasses adblock detection if DNS filtering in kept off  as of now.

**Comment by vishupal4185** [comment]
@PrimePlaya24 If this issue can't be fixed then you should remove the code for Dropgalaxy

**Comment by PrimePlaya24** [comment]
Removed support for DropGalaxy

**Comment by PrimePlaya24** [comment]
Resolved in [v2.1.4](https://github.com/PrimePlaya24/dl-site-scrubber/commit/2b8ddc65750d8096034b3738d87acf94b2b6601e)
