### ISSUE TITLE
[Site Request] apk.miuiku.com

### ISSUE THREAD

**Issue by REDAKUN** [PrimePlaya24/dl-site-scrubber#12]
some links : 
https://apk.miuiku.com/OKg2
https://apk.miuiku.com/LpqC7
https://apk.miuiku.com/Q8YX2pKo

**Comment by PrimePlaya24** [comment]
Added in [f166b66](https://github.com/PrimePlaya24/dl-site-scrubber/commit/f166b66e43414ba06df80e7f88b2f10e0817b9cc)
