### ISSUE TITLE
Thank You!

### ISSUE THREAD

**Issue by fosam** [PrimePlaya24/dl-site-scrubber#13]
Hello Peter

These download website are becoming more popular over time on many different sites, but they are quite a pain to deal with before one gets to download the actual file.

I'm not sure how i found your script but i think i was looking for something on greasy fork, then i stumbled upon your script.

I cannot imagine using those sites without this script, so i thank you every single time i hover my mouse over the download button.

Just a small note, on Chrome (latest version) i have to refresh the page 2-3 times before the script starts working, i noticed this in October-November last year, any thoughts?

Thanks!

**Comment by PrimePlaya24** [comment]
I can look into it. Can you possibly provide more info like which websites in particular and what the console says if there are any errors?

**Comment by fosam** [comment]
Yes, here is screenshot from uploadrar, but the same thing happens on for example Hexupload.

<details>
<summary>Screenshot</summary>
<img src=https://user-images.githubusercontent.com/52612348/160300861-8f229514-b425-4489-9ed1-2cca38866889.png>
</details>

**Comment by PrimePlaya24** [comment]
Awesome. Thank you!

**Comment by fosam** [comment]
Actually, triggering the script after 2-3 page reloads is only if one's lucky, the average is 8-10 times.

I hope you will be able to indentify the issue :)

**Comment by PrimePlaya24** [comment]
Fixed with [95b8265](https://github.com/PrimePlaya24/dl-site-scrubber/commit/95b82650b2614ae29c6433419ad7b1a91569ddad)
