### ISSUE TITLE
Doesn't work in Rapidgator

### ISSUE THREAD

**Issue by davidhdez** [PrimePlaya24/dl-site-scrubber#14]
I can't hover the button 2 sec on Rapidgator

**Comment by PrimePlaya24** [comment]
Updated/fixed in [v2.1.3](https://github.com/PrimePlaya24/dl-site-scrubber/commit/08fa380f90f9399d549b901615fb498da0fbc4ff)

**Comment by davidhdez** [comment]
Still problematic 
![image](https://user-images.githubusercontent.com/4020840/166675454-74ec344b-8cd4-4626-9a86-d638726a1d7f.png)
