### ISSUE TITLE
upload-4ever no longer working

### ISSUE THREAD

**Issue by niemant** [PrimePlaya24/dl-site-scrubber#3]
Site www.upload-4ever.com is still displaying the invisible layer that onclick opens a new website, also the countdown to download is still showing.

**Comment by PrimePlaya24** [comment]
www.upload-4ever.com uses server-side validation which checks the timing. You cannot skip the countdown on this site sadly, unless there is some sneaky way I am unaware of at the moment.

Looking into the clickjacking elements

**Comment by PrimePlaya24** [comment]
https://github.com/PrimePlaya24/dl-site-scrubber/commit/e6bc3a1e389ff6dd78dfff4f097092fe6be6aa9f

Patched.
