### ISSUE TITLE
bypassing time restriction in dropgalaxy

### ISSUE THREAD

**Issue by noahsarkq** [PrimePlaya24/dl-site-scrubber#5]
![asd](https://user-images.githubusercontent.com/86694875/135060198-2d74c12c-aac6-47bb-b748-49087365a889.png)
it can be easily bypassed also in msg id need to be edited everytime, and usr is missing without usr dl not working currently
""
[download adguard unlocked version][rand=][id=g4wjtggy9x5d][dropgalaxyisbest=0][adblock_detected=1][downloadhash=1][downloadhashad=undefined][scr=https://www.blockadsnot.com/tabletop.min.js][scr=https://static.cloudflareinsights.com/beacon.min.js][scr=//tag.vlitag.com/v1/1631505789/85c725d74c296ff96d007f4c38aa2636.js][scr=//assets.vlitag.com/prebid/default/prebid-v5.12.0.js][scr=//www.googletagservices.com/tag/js/gpt.js][scr=//imasdk.googleapis.com/js/sdkloader/ima3.js][scr=//assets.vlitag.com/plugins/safeframe/src/js/sf_host.min.js][scr=https://securepubads.g.doubleclick.net/gpt/pubads_impl_2021090701.js][scr=//dq06u9lt5akr2.cloudfront.net/LcWRlZkROEAwCeUhVUV53Rw%3D%3D][scr=https://c.adsco.re/][scr=//blockadsnot.com/lSO.html?_=BAYAYT6WTAFhPs-VgAGBAsAAIGZh23yxj8kQkT0NUSTGM43iB3_FHu_A7capGL4bcckQwQBGMEQCIAqvnDbsa8fNhTsO03KtctokgIHNzpu6dFYDMTLBawcOAiAyM_89FH3agCMOVen5grgaHAWc-JJyL2gmCVzrHhXtBg&v=4&ZnRgETxI=3901319&minBid=0.001&epchWNqJ=0:1,0&rmKjnsHO=&BFJHMstk=https%3A%2F%2Fdropgalaxy.com%2F827-what-is-insurance-coverage.html&s=1920,1080,1,1920,1080,0]""

**Comment by PrimePlaya24** [comment]
So we can use a template message and replace the `id` with the current requested file id from the download page and then inject the user id as well.

Working on testing this now...

**Comment by PrimePlaya24** [comment]
@noahsarkq Do you mind sharing the python code you used in your post?

**Comment by noahsarkq** [comment]
> @noahsarkq Do you mind sharing the python code you used in your post?

Are you on telegram?

**Comment by PrimePlaya24** [comment]
@noahsarkq https://t.me/PrimePlaya24

**Comment by PrimePlaya24** [comment]
Removed support for DropGalaxy
